from django.urls import path

from . import views

urlpatterns = [
    path("", views.tableau_de_bord, name="tableau_de_bord"),
    path("approvisionnement/", views.approvisionnement, name="approvisionnement"),
    path("echeances/", views.liste, name="liste"),
    path("echeances/export/", views.export_excel, name="export_excel"),
    path("echeances/nouvelle/", views.EcheanceCreate.as_view(), name="echeance_creer"),
    path("echeances/import/", views.importer, name="importer"),
    path("echeances/import/modele/", views.modele_import, name="modele_import"),
    path("echeances/<int:pk>/", views.EcheanceDetail.as_view(), name="echeance_detail"),
    path("echeances/<int:pk>/modifier/", views.EcheanceUpdate.as_view(), name="echeance_modifier"),
    path("echeances/<int:pk>/cloturer/", views.cloturer, name="echeance_cloturer"),
    path("echeances/<int:pk>/rouvrir/", views.rouvrir, name="echeance_rouvrir"),
    path("profil/", views.profil, name="profil"),
    path("audit/", views.journal_audit, name="journal_audit"),
    path("alertes/", views.parametres_alertes, name="parametres_alertes"),
    path("roles/", views.roles, name="roles"),
    path("roles/nouveau/", views.RoleCreate.as_view(), name="role_creer"),
    path("roles/<int:pk>/modifier/", views.RoleUpdate.as_view(), name="role_modifier"),
    path("roles/<int:pk>/supprimer/", views.RoleDelete.as_view(), name="role_supprimer"),
    path("periodes/", views.periodes, name="periodes"),
    path("periodes/nouvelle/", views.PeriodeCreate.as_view(), name="periode_creer"),
    path("periodes/<int:pk>/modifier/", views.PeriodeUpdate.as_view(), name="periode_modifier"),
    path("periodes/<int:pk>/supprimer/", views.PeriodeDelete.as_view(), name="periode_supprimer"),
    path("echeances/<int:pk>/supprimer/", views.EcheanceDelete.as_view(), name="echeance_supprimer"),
    path("banques/<int:pk>/", views.BanqueDetail.as_view(), name="banque_detail"),
    path("banques/<int:pk>/supprimer/", views.BanqueDelete.as_view(), name="banque_supprimer"),
    path("fournisseurs/<int:pk>/", views.FournisseurDetail.as_view(), name="fournisseur_detail"),
    path("fournisseurs/<int:pk>/supprimer/", views.FournisseurDelete.as_view(), name="fournisseur_supprimer"),
    path("utilisateurs/<int:pk>/", views.UtilisateurDetail.as_view(), name="utilisateur_detail"),
    path("utilisateurs/<int:pk>/modifier/", views.UtilisateurUpdate.as_view(), name="utilisateur_modifier"),
    path("utilisateurs/<int:pk>/supprimer/", views.UtilisateurDelete.as_view(), name="utilisateur_supprimer"),
    path("utilisateurs/", views.utilisateurs, name="utilisateurs"),
    path("utilisateurs/nouveau/", views.utilisateur_creer, name="utilisateur_creer"),
    path("banques/", views.banques, name="banques"),
    path("banques/nouvelle/", views.BanqueCreate.as_view(), name="banque_creer"),
    path("banques/<int:pk>/modifier/", views.BanqueUpdate.as_view(), name="banque_modifier"),
    path("fournisseurs/", views.fournisseurs, name="fournisseurs"),
    path("fournisseurs/nouveau/", views.FournisseurCreate.as_view(), name="fournisseur_creer"),
    path("fournisseurs/<int:pk>/modifier/", views.FournisseurUpdate.as_view(), name="fournisseur_modifier"),
]
