# Generated by Django 5.2.17 on 2026-10-02 18:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('code', models.CharField(blank=True, help_text='Ex. : CORIS, BSIC', max_length=20, verbose_name='code court')),
                ('actif', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'banque',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SmsEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('texte', models.CharField(max_length=500)),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS envoyé',
                'verbose_name_plural': 'SMS envoyés',
                'ordering': ['-envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='EnvoiRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destinataire', models.EmailField(max_length=254)),
                ('canal', models.CharField(default='email', max_length=20)),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('nb_echeances', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "envoi d'alerte",
                'verbose_name_plural': "envois d'alertes",
                'ordering': ['-envoye_le'],
                'unique_together': {('date', 'destinataire', 'canal')},
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRAITE_AVALISEE', 'Traite avalisée'), ('TRAITE_SIMPLE', 'Traite simple'), ('CHEQUE', 'Chèque'), ('REGLEMENT', 'Règlement fournisseur')], max_length=20, verbose_name='type')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='n° de chèque ou de traite')),
                ('date_creation', models.DateField(verbose_name='date de création')),
                ('date_echeance', models.DateField(db_index=True, verbose_name="date d'échéance")),
                ('montant', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='montant (F CFA)')),
                ('cout_aval', models.DecimalField(decimal_places=0, default=0, help_text='Uniquement pour les traites avalisées.', max_digits=15, verbose_name="coût d'aval et frais (F CFA)")),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('piece_jointe', models.FileField(blank=True, upload_to='pieces/%Y/%m/', verbose_name='pièce jointe')),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('RENOUVELEE', 'Renouvelée'), ('ANNULEE', 'Annulée')], db_index=True, default='A_VENIR', max_length=20, verbose_name='statut')),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='date de clôture')),
                ('reference_cloture', models.CharField(blank=True, max_length=200, verbose_name='référence (avis bancaire, motif de rejet…)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echeances', to='echeances.banque', verbose_name='banque')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('renouvelee_par', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renouvelle', to='echeances.echeance', verbose_name='renouvelée par')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echeances', to='echeances.fournisseur', verbose_name='fournisseur / bénéficiaire')),
            ],
            options={
                'verbose_name': 'échéance',
                'ordering': ['date_echeance', 'banque__nom'],
                'permissions': [('cloturer_echeance', 'Peut clôturer une échéance (payée, impayée, renouvelée)')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEcheance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRAITE_AVALISEE', 'Traite avalisée'), ('TRAITE_SIMPLE', 'Traite simple'), ('CHEQUE', 'Chèque'), ('REGLEMENT', 'Règlement fournisseur')], max_length=20, verbose_name='type')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='n° de chèque ou de traite')),
                ('date_creation', models.DateField(verbose_name='date de création')),
                ('date_echeance', models.DateField(db_index=True, verbose_name="date d'échéance")),
                ('montant', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='montant (F CFA)')),
                ('cout_aval', models.DecimalField(decimal_places=0, default=0, help_text='Uniquement pour les traites avalisées.', max_digits=15, verbose_name="coût d'aval et frais (F CFA)")),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('piece_jointe', models.TextField(blank=True, max_length=100, verbose_name='pièce jointe')),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('RENOUVELEE', 'Renouvelée'), ('ANNULEE', 'Annulée')], db_index=True, default='A_VENIR', max_length=20, verbose_name='statut')),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='date de clôture')),
                ('reference_cloture', models.CharField(blank=True, max_length=200, verbose_name='référence (avis bancaire, motif de rejet…)')),
                ('cree_le', models.DateTimeField(blank=True, editable=False, verbose_name='créée le')),
                ('modifie_le', models.DateTimeField(blank=True, editable=False, verbose_name='modifiée le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('banque', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='echeances.banque', verbose_name='banque')),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('fournisseur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='echeances.fournisseur', verbose_name='fournisseur / bénéficiaire')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('renouvelee_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='echeances.echeance', verbose_name='renouvelée par')),
            ],
            options={
                'verbose_name': 'historique',
                'verbose_name_plural': 'historical échéances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
