# Generated by Django 5.2.17 on 2026-10-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echeances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banque',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=50, verbose_name='numéro de compte'),
        ),
    ]
