# Generated by Django 5.2.17 on 2026-10-02 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echeances', '0005_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. : 15 prochains jours, 6 prochains mois', max_length=60, verbose_name='libellé')),
                ('jours', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='nombre de jours')),
                ('tableau_de_bord', models.BooleanField(default=False, help_text='Maximum 4 périodes sur le tableau de bord.', verbose_name='afficher sur le tableau de bord')),
                ('actif', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'période',
                'ordering': ['jours'],
            },
        ),
    ]
