# Generated by Django 5.2.17 on 2026-10-03 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echeances', '0008_historique_referentiels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echeance',
            options={'ordering': ['date_echeance', 'banque__nom'], 'permissions': [('cloturer_echeance', 'Peut clôturer une échéance (payée, impayée, renouvelée)'), ('importer_echeance', 'Peut importer des échéances depuis Excel'), ('exporter_echeance', 'Peut exporter la liste des échéances en Excel'), ('voir_approvisionnement', 'Peut consulter les montants à approvisionner')], 'verbose_name': 'échéance'},
        ),
        migrations.CreateModel(
            name='EvenementRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('+', 'Création'), ('~', 'Modification'), ('-', 'Suppression')], max_length=1)),
                ('nom', models.CharField(max_length=150, verbose_name='rôle')),
                ('detail', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'événement de rôle',
                'verbose_name_plural': 'événements de rôles',
                'ordering': ['-date'],
            },
        ),
    ]
