# Generated by Django 5.2.17 on 2026-10-03 10:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echeances', '0009_roles_droits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresAlertes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utiliser', models.BooleanField(default=False, help_text='Décoché, le logiciel utilise les réglages e-mail du serveur (fichier .env).', verbose_name='utiliser ces réglages')),
                ('hote', models.CharField(blank=True, help_text='Ex. : smtp.votre-domaine.com', max_length=200, verbose_name='serveur SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='port')),
                ('securite', models.CharField(choices=[('tls', 'STARTTLS (port 587)'), ('ssl', 'SSL/TLS (port 465)'), ('aucune', 'Aucun (déconseillé)')], default='tls', max_length=10, verbose_name='chiffrement')),
                ('utilisateur', models.CharField(blank=True, max_length=200, verbose_name='identifiant')),
                ('mot_de_passe_chiffre', models.TextField(blank=True)),
                ('mot_de_passe_maj', models.DateTimeField(blank=True, null=True, verbose_name='mot de passe mis à jour le')),
                ('expediteur_nom', models.CharField(default='ÉchéancePro', max_length=100, verbose_name="nom de l'expéditeur")),
                ('expediteur_adresse', models.EmailField(blank=True, max_length=254, verbose_name="adresse de l'expéditeur")),
                ('paliers', models.CharField(default='15,7,3', help_text='Jours séparés par des virgules, ex. : 15,7,3. Les échéances du jour et en retard sont toujours signalées.', max_length=60, verbose_name="paliers d'alerte (jours avant l'échéance)")),
            ],
            options={
                'verbose_name': "paramètres d'alertes",
                'verbose_name_plural': "paramètres d'alertes",
                'permissions': [('gerer_parametres_alertes', 'Peut gérer les paramètres e-mail et les alertes')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalParametresAlertes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('utiliser', models.BooleanField(default=False, help_text='Décoché, le logiciel utilise les réglages e-mail du serveur (fichier .env).', verbose_name='utiliser ces réglages')),
                ('hote', models.CharField(blank=True, help_text='Ex. : smtp.votre-domaine.com', max_length=200, verbose_name='serveur SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='port')),
                ('securite', models.CharField(choices=[('tls', 'STARTTLS (port 587)'), ('ssl', 'SSL/TLS (port 465)'), ('aucune', 'Aucun (déconseillé)')], default='tls', max_length=10, verbose_name='chiffrement')),
                ('utilisateur', models.CharField(blank=True, max_length=200, verbose_name='identifiant')),
                ('mot_de_passe_maj', models.DateTimeField(blank=True, null=True, verbose_name='mot de passe mis à jour le')),
                ('expediteur_nom', models.CharField(default='ÉchéancePro', max_length=100, verbose_name="nom de l'expéditeur")),
                ('expediteur_adresse', models.EmailField(blank=True, max_length=254, verbose_name="adresse de l'expéditeur")),
                ('paliers', models.CharField(default='15,7,3', help_text='Jours séparés par des virgules, ex. : 15,7,3. Les échéances du jour et en retard sont toujours signalées.', max_length=60, verbose_name="paliers d'alerte (jours avant l'échéance)")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historique',
                'verbose_name_plural': "historical paramètres d'alertes",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
