# Generated by Django 5.2.17 on 2026-10-03 11:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echeances', '0010_parametres_alertes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='raison sociale')),
                ('logo', models.ImageField(blank=True, upload_to='entreprise/', verbose_name='logo')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=60, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprise',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEntreprise',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='raison sociale')),
                ('logo', models.TextField(blank=True, max_length=100, verbose_name='logo')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=60, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historique',
                'verbose_name_plural': 'historical entreprise',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
